#!/bin/sh

echo "Starting ${0}"

if [ $# -ne 2 ]; then
  echo "Must get 2 params"
  echo " - wait duration"
  echo " - location to use"
  exit 1
fi

WAITDURATION=${1}
LOCATIONTOUSE=${2}

echo "Passed locaiton is ${LOCATIONTOUSE}"

if [ ! -f ${LOCATIONTOUSE} ]; then
  echo "Error - passed location dosen't exist"
  exit 1
fi

cd ${LOCATIONTOUSE}
echo "Changed current location to $(pwd)"

echo "Waiting for ${WAITDURATION} to allow other container to start..."
sleep ${WAITDURATION}
echo "Wait over"
nosetests --rednose .
exit $?
